= LAW XX
:date: 2025-10-26
:summary: The 20th Linguistic Annotation Workshop


++++
<h1>LAW XX (2026)</h1>
++++

Linguistic annotation of natural language corpora is the backbone of supervised methods of statistical natural language processing.
The **L**inguistic **A**nnotation **W**orkshop (**LAW**) is the annual workshop of the **ACL and ELRA Special Interest Group on Annotation (SIGANN)**, and it provides a forum for the presentation and discussion of innovative research on all aspects of linguistic annotation, including the creation and evaluation of annotation schemes, methods for automatic and manual annotation, use and evaluation of annotation software and frameworks, representation of linguistic data and annotations, semi-supervised “human in the loop” methods of annotation, crowd-sourcing approaches, and more.
As in the past, the LAW will provide a forum for annotation researchers to work towards standardization, best practices, and interoperability of annotation information and software.

[.dates-callout]
--
.Important Dates
All submission deadlines are 11:59 p.m. UTC-12:00 ("anywhere on Earth").

* *Submission deadline*: TBD
* *Notification of acceptance*: TBD
* *Camera-ready papers due*: TBD
* *Workshop Date*: TBD
--
