#!/usr/bin/env python3
"""Generate content/accepted.adoc from papers.yml.

papers.yml is the authoritative source (titles, authors, abstracts). It also
holds private data (emails) and is gitignored — only public fields are emitted.
Run from the repo root:  python3 scripts/build_accepted.py
"""
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "papers.yml"
OUT = ROOT / "content" / "accepted.adoc"

# LaTeX -> plain-text symbol replacements applied inside math/escapes.
SYMBOLS = {
    r"\rightarrow": "→",
    r"\leftarrow": "←",
    r"\kappa": "κ",
    r"\alpha": "α",
    r"\beta": "β",
    r"\times": "×",
}


def clean(text: str) -> str:
    """Strip common LaTeX artifacts so the abstract reads as plain prose."""
    t = text.strip()
    # Resolve \url{...} before \footnote{...} so nested braces don't trip us up.
    t = re.sub(r"\\url\{([^}]*)\}", r"\1", t)
    t = re.sub(r"\\footnote\{\s*([^}]*?)\s*\}", r" (\1)", t)
    # Text-styling commands: keep the content, drop the markup.
    t = re.sub(r"\\(?:textit|textbf|emph|texttt|textsc)\{([^}]*)\}", r"\1", t)
    for tex, char in SYMBOLS.items():
        t = t.replace(tex, char)
    # Escaped punctuation.
    for esc, ch in ((r"\%", "%"), (r"\#", "#"), (r"\&", "&"), (r"\_", "_"),
                    (r"\$", "$")):
        t = t.replace(esc, ch)
    # Drop remaining inline-math delimiters (content already de-TeXed above).
    t = t.replace("$", "")
    # LaTeX doubled close-quote used as a possessive apostrophe.
    t = t.replace("''", "'")
    # Normalise whitespace (abstracts have trailing newlines/indentation).
    t = re.sub(r"\s+", " ", t).strip()
    return t


def author_name(a: dict) -> str:
    return f"{a['first_name']} {a['last_name']}".strip()


def institutions(authors: list) -> list:
    """Unique institutions in order of first appearance."""
    seen, out = set(), []
    for a in authors:
        inst = (a.get("institution") or "").strip()
        if inst and inst not in seen:
            seen.add(inst)
            out.append(inst)
    return out


def render_paper(p: dict, lines: list) -> None:
    title = clean(str(p["title"]))
    names = ", ".join(author_name(a) for a in p["authors"])
    insts = "; ".join(institutions(p["authors"]))
    abstract = clean(str(p["abstract"]))
    anthology = (p.get("anthology") or "").strip()
    # Linking the title doesn't change asciidoctor's auto-generated heading
    # ID, so program.adoc's cross-page anchors keep working.
    heading = f"link:{anthology}[{title}]" if anthology else title

    lines.append("[discrete]")
    lines.append(f"=== {heading}")
    lines.append("")
    lines.append(f"*{names}*")
    lines.append("")
    if insts:
        lines.append(f"_{insts}_")
        lines.append("")
    lines.append(abstract)
    lines.append("")


def main() -> None:
    papers = yaml.safe_load(SRC.read_text(encoding="utf-8"))
    papers.sort(key=lambda p: p["id"])

    # Papers with `archival: false` are presented at LAW but published in
    # another venue, so they go under their own header.
    archival = [p for p in papers if p.get("archival", True) is not False]
    non_archival = [p for p in papers if p.get("archival", True) is False]

    lines = [
        "= LAW XX | Accepted Papers",
        ":date: 2025-10-26",
        ":summary: LAW XX | Accepted Papers",
        "",
        "++++",
        "<h1>Accepted Papers</h1>",
        "++++",
        "",
        "// This file is generated by scripts/build_accepted.py from papers.yml.",
        "// Edit the source data and regenerate; do not hand-edit.",
        "",
    ]

    for p in archival:
        render_paper(p, lines)

    if non_archival:
        lines.append("== Non-Archival Papers")
        lines.append("")
        lines.append("_Accepted in Findings, presented at LAW XX_")
        lines.append("")
        for p in non_archival:
            render_paper(p, lines)

    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} with {len(archival)} archival "
          f"and {len(non_archival)} non-archival papers.")


if __name__ == "__main__":
    main()
